### ISSUE TITLE
KeyError in gotConfig needs traceback

### ISSUE THREAD

**Issue by jimboca** [Einstein42/udi-polyglot-interface#1]
Would be nice to print the traceback to where this happens:
2018-01-15 20:49:13,988 ERROR    KeyError in gotConfig: '27812007'

**Comment by jimboca** [comment]
To help me debug my issue, I added the full traceback.  Not sure if this is best, but it's what I added:

```
from traceback import format_exception
...
        try:
            for watcher in self.__configObservers:
                watcher(config)
        except KeyError as e:
            exc_type, exc_value, exc_traceback = sys.exc_info()
            err_str = ''.join(format_exception(exc_type, exc_value, exc_traceback))
            LOGGER.error('KeyError in gotConfig: {}'.format(err_str))
```

So I can find where my issue is.

```
2018-01-16 17:47:25,719 ERROR    KeyError in gotConfig: Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/polyinterface/polyinterface.py", line 373, in inConfig
    watcher(config)
  File "/home/pi/.local/lib/python3.5/site-packages/polyinterface/polyinterface.py", line 530, in _gotConfig
    self.start()
  File "/home/pi/development/udi-harmony-poly/harmony_hub_nodes/HarmonyController.py", line 104, in start
    self.add_hub_from_customData(item['address'])
  File "/home/pi/development/udi-harmony-poly/harmony_hub_nodes/HarmonyController.py", line 255, in add_hub_from_customData
    return self.add_hub(address,ndata['name'],ndata['host'],ndata['port'])
  File "/home/pi/development/udi-harmony-poly/harmony_hub_nodes/HarmonyController.py", line 239, in add_hub
    self.addNode(HarmonyHub(self, address, name, host, port))
  File "/home/pi/.local/lib/python3.5/site-packages/polyinterface/polyinterface.py", line 605, in addNode
    self.nodes[node.address].start()
  File "/home/pi/development/udi-harmony-poly/harmony_hub_nodes/HarmonyHub.py", line 75, in start
    self.query();
  File "/home/pi/development/udi-harmony-poly/harmony_hub_nodes/HarmonyHub.py", line 85, in query
    self._get_current_activity()
  File "/home/pi/development/udi-harmony-poly/harmony_hub_nodes/HarmonyHub.py", line 113, in _get_current_activity
    self._set_current_activity(ca)
  File "/home/pi/development/udi-harmony-poly/harmony_hub_nodes/HarmonyHub.py", line 256, in _set_current_activity
    self.parent.nodes[str(id)]._set_st(1)
KeyError: '27812007'
```

**Comment by jimboca** [comment]
No idea if that is the best way to print the traceback, but it works.
