### ISSUE TITLE
No traceback from some errors

### ISSUE THREAD

**Issue by jimboca** [Einstein42/udi-polyglot-interface#2]
I don't get a traceback for this unless I run in the foreground.  We need polyglot to print this to make user debugging possible.

```
pi@rpi3-2:~/.polyglot/nodeservers/HarmonyHub $ ./harmony_hub.py
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/paho/mqtt/client.py", line 2650, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/home/pi/.local/lib/python3.5/site-packages/paho/mqtt/client.py", line 1481, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/home/pi/.local/lib/python3.5/site-packages/paho/mqtt/client.py", line 1003, in loop
    rc = self.loop_read(max_packets)
  File "/home/pi/.local/lib/python3.5/site-packages/paho/mqtt/client.py", line 1284, in loop_read
    rc = self._packet_read()
  File "/home/pi/.local/lib/python3.5/site-packages/paho/mqtt/client.py", line 1849, in _packet_read
    rc = self._packet_handle()
  File "/home/pi/.local/lib/python3.5/site-packages/paho/mqtt/client.py", line 2305, in _packet_handle
    return self._handle_publish()
  File "/home/pi/.local/lib/python3.5/site-packages/paho/mqtt/client.py", line 2500, in _handle_publish
    self._handle_on_message(message)
  File "/home/pi/.local/lib/python3.5/site-packages/paho/mqtt/client.py", line 2647, in _handle_on_message
    self.on_message(self, self._userdata, message)
  File "/home/pi/.local/lib/python3.5/site-packages/polyinterface/polyinterface.py", line 200, in _message
    self.inConfig(parsed_msg[key])
  File "/home/pi/.local/lib/python3.5/site-packages/polyinterface/polyinterface.py", line 372, in inConfig
    watcher(config)
  File "/home/pi/.local/lib/python3.5/site-packages/polyinterface/polyinterface.py", line 527, in _gotConfig
    self.start()
  File "/home/pi/development/udi-harmony-poly/harmony_hub_nodes/HarmonyController.py", line 85, in start
    if vl.amount == 1:
NameError: name 'vl' is not defined
```

**Comment by jimboca** [comment]
This was fixed a while back.
